### ISSUE TITLE
TSS comparison must be numeric

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/lisflood-utilities#11]
Currently, tss comparison is text based which means that any single difference in files will make a test fail.
Need to compare value by value with rtol.

In same branch, will add possibility to instantiate comparators (NetCDF and TSS) for bit identical comparisons.

**Comment by salampe** [comment]
Comparing values with rtol is good but sometimes you want everything to be bit identical (@ecCinziaMazzetti  likes that ;) ). Maybe you could have "two levels" of test results: 
identical - fail/pass
values with rtol - fail/pass
In this way the user of the test can decide for himself if for his purpose the test failed or passed (e.g. if you just change something not changing the output you would expect bit identical results whereas if you change something that will modify also the output you might be ok if values are equal within a certain tolerance range).

**Comment by domeniconappo** [comment]
Yes @salampe 
I think having two kind of tests like that in TSS comparison is a good thing.
I will also try to introduce the same in netcdf/numpy arrays comparisons, where I use numpy.allclose boolean functions with rtol and atol, instead of `array_equal`. 
We always need to take into account intrinsic imprecision of floating point operations, which can lead to (very small) differences on different systems, so `bit identity` can be not achievable in tests.
